[package]
name = "U256"
version = "0.3.3"

[dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "1570509e746b6626264cb6e9c0c8371683253961"
subdir = "aptos-move/framework/move-stdlib"
addr_subst = { std = "0x1" }

[addresses]
u256 = "43417434fd869edee76cca2a4d2301e528a1551b1d719b75c350c3c97d15b8b9"